//Array com frases para o bot twittar
const frases = [
    'ヽ(⌐■_■)ノ♪♬ ᴾʳᵒᶤᵇᶤᵈᵃ ᵖʳᵃ ᵐᶤᵐ ᶰᵒ ʷᵃʸ ♬♪♫',
    '[̲̅P̲̅][̲̅r̲̅][̲̅o̲̅][̲̅i̲̅][̲̅b̲̅][̲̅i̲̅][̲̅d̲̅][̲̅a̲̅] [̲̅p̲̅][̲̅r̲̅][̲̅a̲̅] [̲̅m̲̅][̲̅i̲̅][̲̅m̲̅] [̲̅n̲̅][̲̅o̲̅] [̲̅w̲̅][̲̅a̲̅][̲̅y̲̅]',
    '▂▃▄▅▆▇█▓▒░Proibida pra mim no way░▒▓█▇▆▅▄▃▂',
    'ᴾʳᵒᶦᵇᶦᵈᵃ ᵖʳᵃ ᵐᶦᵐ ⁿᵒ ʷᵃʸ',
    'Ƈσмρℓєтαмєηтє ℓσυcσ ( ಠ_ಠ)  мαѕ υм ℓσυcσ cσηѕcιєηтє ╭∩╮（︶︿︶）╭∩╮',
    'C O M P L E T A M E N T E  L O U C O ᵐᵃˢ ᵘᵐ ˡᵒᵘᶜᵒ ᶜᵒⁿˢᶜᶦᵉⁿᵗᵉ',
    'SANTOS',
    'SKATE',
    'EU VOU FAZER DE UM SKATE QUE ELA NÃO VAI SKATEEEEE',
    'EU VOU FAZER DE UM JEITO QUE ELA NÃO VAI ESQUECEEEER',
    'PaReCiA iNoFeNsIvA mAs Te DoMiNou',
    'Parecia inofensiva 𝕞𝕒𝕤 𝕥𝕖 𝕕𝕠𝕞𝕚𝕟𝕠𝕦',
    'Só os loucos sabem? Só os loucos sabem!!!',
    'O homem quando está com skate não quer skate com ninguem',
    'EU FALO CHARLIE VOCÊS FALAM BROWN',
    'Dias de luta dias de etc',
    'DIAS DE LUTA DIAS DE LUTA DIAS DE LUTA DIAS DE LUTA DIAS DE LUTA DIAS DE LUTA DIAS DE LUTA DIAS DE LUTA DIAS DE LUTA',
    'S̫̣̮ᴏ̪̹̋̓͆͌ ͓̺̌ᴏ͙̼ͥ̿̈ͪ̌͐s͓̤͛͒͊ͯ̈̉ ̅̂͊ͤʟ̱͈̩͖ᴏ͖̜̦̬͌ᴜ͖̲̲̾͂̆̓ᴄ̊͗̚ᴏ͚͍̹̟́̚s͔̙̰͂͛̿ͨͤ ͔̦ͨ̐s͍̺̞̆͛̓ᴀ̰̠͐ͮͭʙ̣̺̤̬͂͐̚ᴇ̥̙ͧ͗ᴍ͙̂͆',
    'Ƨ͚̭̈Ơ͉͎̆ͬͣͩ͐ ̝͙̖̀Ơ̟̗̙͙̄ͨͨƧ͚̰̼̼̇ ͚͕ͧ̿Լ̥̉̓̃ͤƠ͇̺̫͎̿Ʋ̝ͥ̐Ƈ̅̄̂͂Ơ̼̭͓͋͌Ƨ͎͎ͮ̎ ̝͍̖͈̲̓Ƨ̝̼̭̄ͅƛ̦͔̘̞̗ͣƁ̯͎̐̄̎ͣЄ̫̦ͤ͗̍̌̐M̟̞̗̍̏̊̂ͅ',
    'Mas ela vai voltar......................................................................................................................................................................................................................',
    "(◦'ںˉ◦) 𝕄𝕒𝕤 𝕖𝕝𝕒 𝕧𝕒𝕚 𝕧𝕠𝕝𝕥𝕒𝕣 (◦'ںˉ◦)",
    '(っ◔◡◔)っ ♥ ᴹᵃˢ ᵉˡᵃ ᵛᵃᶤ ᵛᵒˡᵗᵃʳ.............',
    'ヽ(⌐■_■)ノ♪♬ ᙓᒪᗩ ᙓ ᗪISᙅᖇᙓTᗩ ᙓ ᙅᙀᒪTᙀᗩ ᙖOᑎS ᒪIᐯᖇOS ᙓ ᗩᙏᗩ OS ᗩᑎIᙏᗩIS, Tᗩ ᒪIᘜᗩᗪO ᙓᙀ SOᙀ O ᙖIᙅᕼO ♬♪♫',
    'Ta ligado eu sou o lixo',
    '(╥﹏╥) 𝙼𝚒𝚗𝚑𝚊 𝚖𝚎𝚗𝚝𝚎 𝚗𝚎𝚖 𝚜𝚎𝚖𝚙𝚛𝚎 𝚝𝚊𝚘 𝚕𝚞𝚌𝚒𝚍𝚊 𝚏𝚎𝚣 𝚎𝚕𝚊 𝚜𝚎 𝚊𝚏𝚊𝚜𝚝𝚊𝚛 (╥﹏╥)',
    'Minha mente nem sempre tão lucida fez etc',
    'Ela achou meu skate engraçado',
    'CHAAAARLIE BROOOOOOOOOOOWNNNNNNNNNNNNNNNNNN',
    '(◐ ε ◑) ᑕᕼᗩᗩᗩᗩᗩᗩᗩᗩᖇᒪIᕮ ᗷᖇOOOOOOOᗯᑎᑎᑎᑎᑎᑎᑎᑎᑎᑎᑎ (◐ ε ◑)',
    '𝓢̯́̄̈́ͭ𝓚̜̝̼ͨ̌͐̈́𝓐͔̀̄𝓣̣͉̿͋𝓔̹ͩͦ͑ͮͮ',
    'S̭̮̮̑̓K̲̬͕͛ͬ̃̎ᗩ̣̰ͩͬ̿T̥ͧ̇ᕮ̤̿͑͗͐ͣ',
    'UH UH SANTOSSSSSSS',
    'CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN CHARLIE BROWN ',
    'SKATE SKAAAATE',
    'Quanto mais a gente rala mais a gente ｃｒｅｓｃｅ',
    'ME ENCONTRAAAAAAAAAAA OU DEIXA EU TE ENCONTRAAAAAR',
    'Tu me apresenta essa mulher meu irmão te dava até um ☆ (͡° ͜ʖ ͡°) 𝚍𝚘𝚌𝚎 (͡° ͜ʖ ͡°) ☆',
    '𝔸ℍ𝔼 𝔸ℍ𝔼 𝔸ℍ𝔼 𝔸ℍ𝔼 𝔸ℍ𝔼 𝔸ℍ𝔼 ',
    ' ( ˘ ³˘)❤ 𝓣𝓪𝓸 𝓷𝓪𝓽𝓾𝓻𝓪𝓵 𝓺𝓾𝓪𝓷𝓽𝓸 𝓪 𝓵𝓾𝔃 𝓭𝓸 𝓭𝓲𝓪 ( ˘ ³˘)❤ ',
    'UH UH CHARLIE UH UH BROWN',
    'Se não eu quem vai fazer você feliz...... G̞̚ͅȔ͙ͭE̪̬͍ͥ̅R̠̙̀ͪ̓̾R̞̱͗̀͛Ä̖ͯ͊   ̫͇ͧ͑ ლ(ಠ益ಠლ)',
    'MEU TU NÃO SABE O QUE ACONTECEU!!!!',
    'MEU TU NÃO SABE O QUE ACONTECEU.....  ಥ_ಥ  ＯＳ ＣＡＲＡＳ ＤＯ ＣＨＡＲＬＩＥ ＢＲＯＷＮ ＩＮＶＡＤＩＲＡＭ Ａ ＣＩＤＡＤＥ ಥ_ಥ ',
    'O CORO VAI COMÊ!!!',
    'E U  F A L O  T U D O  Q U E  E L A  G O S T A  D E  E S C U T A R',
    '✰ Só por uma noite............................... ✰',
    'Mas só de ouvir a sua voz eu já me sinto bem ♥‿♥',
    'VOOU TE LEVAAAAR YEAAAAAAAAAAAAAAAAAH',
    'TE LEVAR DAQUIIIIII',
    'Eu nasci pobre ಠ_ಠ  mas não nasci otário (/‾▿‾)/',
    'JUNTA SUA MÃE SEU CACHORRO E SUA SOGRA O CORO VAI COMÊ',
    'M U L H E R A D A  M U I T O  L O U C A  C O M  D O C E  N A  B O C A',
    "𝕃𝕚𝕧𝕣𝕖 𝕡𝕣𝕒 𝕡𝕠𝕕𝕖𝕣 𝕤𝕠𝕣𝕣𝕚𝕣 (◦'ںˉ◦) ",
    '(⌐■_■) ᒪIᐯᖇᕮ ᑭᖇᗩ ᑭOᗪᕮᖇ ᗷᑌSᑕᗩᖇ O ᗰᕮᑌ ᒪᑌGᗩᖇ ᗩO SOᒪ (⌐■_■)'
];

module.exports = frases    //Exportando o array para ser utilizado em outro arquivo